"use client";

import { useState, useEffect, useRef, memo } from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import Image from "next/image";
import ChatInput, { ImageAttachment } from "@/components/ChatInput";
import dynamic from "next/dynamic";
import { Thought } from "@/components/ThoughtStream";
import { calculateInfluence } from "@/lib/diff";
import { ConversationTurn } from "@/lib/gemma";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Sparkles, Info, Camera, FileCode, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";
import GemmaLogo from "@/components/GemmaLogo";
import ClickSpark from "@/components/ClickSpark";

const ThoughtStream = dynamic(() => import("@/components/ThoughtStream"), { ssr: false });
const AnswerPanel = dynamic(() => import("@/components/AnswerPanel"), { ssr: false });
const InfluenceScore = dynamic(() => import("@/components/InfluenceScore"), { ssr: false });

type AppState = "idle" | "streaming" | "locked" | "collapsed" | "answered" | "error";

type Exchange = {
  id: string;
  userMessage: string;
  image?: ImageAttachment;
  thoughts: Thought[];
  answer: string;
  influenceScore: number;
  totalThoughts: number;
  changedThoughts: number;
};

export default function Home() {
  const [appState, setAppState] = useState<AppState>("idle");
  const isProcessing = useRef(false);
  const [exchanges, setExchanges] = useState<Exchange[]>([]);
  const [currentMessage, setCurrentMessage] = useState("");
  const [userInput, setUserInput] = useState("");
  const [currentImage, setCurrentImage] = useState<ImageAttachment | undefined>();
  const [currentThoughts, setCurrentThoughts] = useState<Thought[]>([]);
  const [currentAnswer, setCurrentAnswer] = useState("");
  const endRef = useRef<HTMLDivElement>(null);
  const footerRef = useRef<HTMLElement>(null);
  const isFooterInView = useInView(footerRef, {
    amount: 0.1,
  });

  // Hard Caching: Persistent Intelligence History (Deferred for performance)
  useEffect(() => {
    const loadHistory = () => {
      const saved = localStorage.getItem("dead_star_history");
      if (saved) {
        try {
          setExchanges(JSON.parse(saved));
        } catch (e) {
          console.warn("Failed to load history cache", e);
        }
      }
    };

    if (window.requestIdleCallback) {
      window.requestIdleCallback(loadHistory);
    } else {
      setTimeout(loadHistory, 200);
    }
  }, []);

  useEffect(() => {
    if (exchanges.length > 0) {
      localStorage.setItem("dead_star_history", JSON.stringify(exchanges));
    }
  }, [exchanges]);

  const downloadDossier = (ex: Exchange) => {
    const content = `
# DEAD STAR: INTELLIGENCE DOSSIER
ID: ${ex.id}
Timestamp: ${new Date().toISOString()}

## USER INPUT
${ex.userMessage}
${ex.image ? `[Multimodal Attachment: ${ex.image.mimeType}]` : ""}

## INTERCEPTED REASONING NODES
${ex.thoughts.map((t, i) => `
### Node ${i + 1} ${t.originalContent && t.originalContent !== t.content ? "(INTERCEPTED)" : ""}
${t.content}
${t.originalContent && t.originalContent !== t.content ? `\n*Original Machine Intent:* ${t.originalContent}` : ""}
`).join("\n")}

## SYNTHESIZED INTELLIGENCE
${ex.answer}

## METRICS
- Influence Score: ${ex.influenceScore}%
- Nodes Processed: ${ex.totalThoughts}
- Human Interventions: ${ex.changedThoughts}

---
Generated by Dead Star (Gemma 4 Native Reasoning Protocol)
`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dead_star_dossier_${ex.id.slice(0, 8)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };


  useEffect(() => {
    // Disabled aggressive auto-scrolling during generation
    // if (appState !== "idle") {
    //   endRef.current?.scrollIntoView({ behavior: "smooth" });
    // }
  }, [currentThoughts, currentAnswer, appState]);

  const handleSend = async (message: string, image?: ImageAttachment) => {
    if (isProcessing.current) return;
    
    // Hard Caching: Instant resolution for repeated queries
    const saved = localStorage.getItem("dead_star_history");
    if (saved) {
      try {
        const parsed: Exchange[] = JSON.parse(saved);
        const cached = parsed.find(ex => ex.userMessage.trim().toLowerCase() === message.trim().toLowerCase());
        if (cached) {
          // Instant Resolution from Cache
          setExchanges(prev => [cached, ...prev]);
          setUserInput("");
          setAppState("idle");
          // No need to set isProcessing.current = false here as it hasn't been set yet
          return;
        }
      } catch (e) {
        console.warn("Cache resolution failed", e);
      }
    }

    isProcessing.current = true;
    
    let updatedExchanges = exchanges;
    if (appState === "answered") {
      const changed =
        currentThoughts.filter(t => t.originalContent !== null && t.originalContent !== t.content).length +
        currentThoughts.filter(t => t.originalContent === "..." && t.content !== "...").length;
      const archived: Exchange = {
        id: Math.random().toString(),
        userMessage: currentMessage,
        image: currentImage,
        thoughts: currentThoughts,
        answer: currentAnswer,
        influenceScore: calculateInfluence(
          currentThoughts.map(t => t.originalContent ?? t.content),
          currentThoughts.map(t => t.content)
        ),
        totalThoughts: currentThoughts.length,
        changedThoughts: changed,
      };
      updatedExchanges = [...exchanges, archived];
      setExchanges(updatedExchanges);
    }

    setAppState("streaming");
    setCurrentMessage(message);
    setUserInput("");
    setCurrentImage(image);
    setCurrentThoughts([]);
    setCurrentAnswer("");

    const history: ConversationTurn[] = [];
    for (const ex of updatedExchanges) {
      const userParts: ConversationTurn["parts"] = [];
      if (ex.image) {
        userParts.push({ inlineData: { mimeType: ex.image.mimeType, data: ex.image.base64 } });
      }
      userParts.push({ text: ex.userMessage });
      history.push({ role: "user", parts: userParts });
      history.push({ role: "model", parts: [{ text: ex.answer }] });
    }

    try {
      // Add a 25s timeout for the client to allow server-side model rotation
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 25000);
      const res = await fetch("/api/think", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message, image, history }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        const errorText = await res.text();
        throw new Error(errorText || `Server error: ${res.status}`);
      }

      if (!res.body) throw new Error("No response body");

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let rawText = "";

      const parseStreamingThoughts = (raw: string) => {
        const extracted: string[] = [];
        let inString = false;
        let currentThought = "";
        let escapeNext = false;
        for (let i = 0; i < raw.length; i++) {
          const char = raw[i];
          if (escapeNext) { currentThought += char; escapeNext = false; continue; }
          if (char === "\\") { escapeNext = true; continue; }
          if (char === '"') {
            if (inString) { extracted.push(currentThought); currentThought = ""; inString = false; }
            else { inString = true; }
          } else if (inString) { currentThought += char; }
        }
        if (inString) extracted.push(currentThought);
        return { extracted, isStreamingThought: inString };
      };

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        rawText += decoder.decode(value, { stream: true });
        const { extracted, isStreamingThought } = parseStreamingThoughts(rawText);
        const cappedExtracted = extracted.slice(0, 6);
        setCurrentThoughts(cappedExtracted.map((text, i) => ({
          id: `thought-${i}`,
          content: text,
          originalContent: null,
          isStreaming: i === cappedExtracted.length - 1 && isStreamingThought && extracted.length <= 6,
        })));
      }
      setCurrentThoughts(prev => prev.map(t => ({ ...t, isStreaming: false })));
      setAppState("locked");
    } catch (err) {
      console.error(err);
      setAppState("error");
    } finally {
      isProcessing.current = false;
    }
  };

  const handleAnswer = async () => {
    if (isProcessing.current) return;
    isProcessing.current = true;
    setAppState("collapsed");
    
    const history: ConversationTurn[] = [];
    const relevantExchanges = exchanges.slice(-4);
    for (const ex of relevantExchanges) {
      const userParts: ConversationTurn["parts"] = [];
      if (ex.image) {
        userParts.push({ inlineData: { mimeType: ex.image.mimeType, data: ex.image.base64 } });
      }
      userParts.push({ text: ex.userMessage });
      history.push({ role: "user", parts: userParts });
      history.push({ role: "model", parts: [{ text: ex.answer }] });
    }

    try {
      setCurrentAnswer("");
      const res = await fetch("/api/answer", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: currentMessage,
          thoughts: currentThoughts.map(t => t.content),
          image: currentImage,
          history,
        }),
      });

      if (!res.ok) {
        const errorText = await res.text();
        throw new Error(errorText || `Server error: ${res.status}`);
      }

      if (!res.body) throw new Error("No response body");
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let pendingAnswer = "";
      let lastUpdateTime = 0;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        pendingAnswer += decoder.decode(value, { stream: true });
        
        const now = Date.now();
        if (now - lastUpdateTime > 20) { // Throttle updates to ~50fps for premium smoothness
          setCurrentAnswer(pendingAnswer);
          lastUpdateTime = now;
        }
      }
      setCurrentAnswer(pendingAnswer); // Final sync
      setAppState("answered");
    } catch (err) {
      console.error(err);
      setAppState("error");
    } finally {
      isProcessing.current = false;
    }
  };

  const handleRetry = () => {
    if (appState === "error") {
      if (currentThoughts.length === 0) {
        handleSend(currentMessage, currentImage);
      } else {
        handleAnswer();
      }
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col relative overflow-x-hidden">
      <ClickSpark
        sparkColor='#fff'
        sparkSize={10}
        sparkRadius={15}
        sparkCount={8}
        duration={400}
      >
      <div className="star-mesh" />
      <div className="star-grid" />
      {/* Centered Floating Solidroad Nav */}
      <div className="fixed top-6 left-1/2 -translate-x-1/2 w-full max-w-[1200px] px-6 z-[500]">
        <nav className="solidroad-nav grid grid-cols-2 md:grid-cols-3 items-center px-6 md:px-10">
          <div className="hidden md:flex items-center gap-4">
            <div className="group relative">
              <div className="flex items-center gap-3 cursor-help opacity-70 hover:opacity-100 transition-opacity">
                <Info className="w-4 h-4 text-primary" />
                <span className="text-[11px] font-subheading font-bold text-muted uppercase tracking-widest">Service Details</span>
              </div>
              <div className="absolute left-0 top-full mt-5 w-80 p-6 rounded-3xl bg-background/95 backdrop-blur-2xl border border-border shadow-2xl opacity-0 translate-y-2 pointer-events-none group-hover:opacity-100 group-hover:translate-y-0 group-hover:pointer-events-auto transition-all duration-300 z-[300] text-left">
                <p className="text-[13px] leading-relaxed text-muted font-body tracking-normal normal-case">
                  <strong className="text-primary block mb-2 text-sm font-subheading uppercase tracking-wider">Guided Reasoning Service</strong>
                  Dead Star provides a high-fidelity partnership with **Gemma 4**, allowing you to refine and co-create complex intelligence streams. Experience the next generation of collaborative reasoning.
                </p>
                <div className="mt-4 pt-4 border-t border-border/50 flex items-center justify-between text-[11px] font-subheading font-bold text-muted uppercase tracking-widest">
                  <span>Protocol: RIP v1.0</span>
                  <span className="text-primary font-black">Active</span>
                </div>
              </div>
            </div>
          </div>

          <div className="flex items-center justify-center gap-3">
            <div className="flex items-center gap-3">
              <GemmaLogo size={32} priority />
              <span className="font-heading font-bold text-lg md:text-xl tracking-tight uppercase">Dead Star</span>
            </div>
            
          </div>

          <div className="flex items-center justify-end gap-6 md:gap-10">
            {/* Entropy UX */}
            <div className="flex flex-col items-end group relative cursor-help">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-subheading font-bold text-primary uppercase tracking-[0.2em]">Entropy</span>
                <div className={cn(
                  "w-1 h-3 rounded-full transition-all duration-300",
                  appState === "streaming" ? "bg-primary animate-pulse" : "bg-muted"
                )} />
              </div>
              <div className="flex items-center gap-1.5">
                <span className="text-xs md:text-sm font-mono font-bold text-foreground tabular-nums">
                  {Math.floor((exchanges.reduce((acc, ex) => acc + ex.userMessage.length + ex.answer.length, 0) + currentMessage.length + currentAnswer.length + currentThoughts.reduce((acc, t) => acc + t.content.length, 0)) / 4).toLocaleString()}
                </span>
                <span className="text-[10px] font-black text-primary/60">TK</span>
              </div>
              <div className="absolute right-0 top-full mt-2 w-48 p-3 rounded-xl bg-background/95 backdrop-blur-2xl border border-border shadow-2xl opacity-0 translate-y-1 pointer-events-none group-hover:opacity-100 group-hover:translate-y-0 group-hover:pointer-events-auto transition-all text-left z-[300]">
                <p className="text-[10px] leading-relaxed text-muted font-body">
                  Real-time measurement of system disorder. Represents the total amount of intercepted tokens processed.
                </p>
              </div>
            </div>

            {/* Context Depth UX */}
            <div className="hidden sm:flex flex-col items-end group relative cursor-help">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-subheading font-bold text-primary uppercase tracking-[0.2em]">Context</span>
                <div className="flex gap-0.5">
                  {[1, 2, 3, 4].map((i) => (
                    <div key={i} className="w-1 h-1 rounded-full bg-primary" />
                  ))}
                </div>
              </div>
              <span className="text-xs md:text-sm font-mono font-bold text-foreground tabular-nums">
                128<span className="text-[11px] ml-0.5 opacity-60">k</span>
              </span>
              <div className="absolute right-0 top-full mt-2 w-48 p-3 rounded-xl bg-background/95 backdrop-blur-2xl border border-border shadow-2xl opacity-0 translate-y-1 pointer-events-none group-hover:opacity-100 group-hover:translate-y-0 group-hover:pointer-events-auto transition-all text-left z-[300]">
                <p className="text-[10px] leading-relaxed text-muted font-body">
                  Gemma 4 Native Long Context enabled. Currently holding <span className="text-primary font-bold">131,072 tokens</span> in active reasoning memory.
                </p>
              </div>
            </div>

            <div className="hidden sm:block w-px h-8 bg-border/40" />

            {/* Nodes UX */}
            <div className="hidden sm:flex flex-col items-end group relative cursor-help">
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-subheading font-bold text-primary uppercase tracking-[0.2em]">Nodes</span>
                <div className={cn(
                  "w-2 h-2 rounded-full border border-primary/40",
                  (currentThoughts.length > 0 || appState === "streaming") && "bg-primary animate-ping"
                )} />
              </div>
              <span className="text-xs md:text-sm font-mono font-bold text-foreground tabular-nums">
                {exchanges.reduce((acc, ex) => acc + ex.thoughts.length, 0) + currentThoughts.length}
              </span>
              <div className="absolute right-0 top-full mt-2 w-48 p-3 rounded-xl bg-background/95 backdrop-blur-2xl border border-border shadow-2xl opacity-0 translate-y-1 pointer-events-none group-hover:opacity-100 group-hover:translate-y-0 group-hover:pointer-events-auto transition-all text-left z-[300]">
                <p className="text-[10px] leading-relaxed text-muted font-body">
                  Active reasoning nodes. Represents the individual cognitive steps and logical inferences made during processing.
                </p>
              </div>
            </div>
          </div>
        </nav>
        {exchanges.length > 0 && (
          <div className="mt-2 pl-6 md:pl-10 flex justify-start">
            <button 
              onClick={() => {
                if (confirm("Clear all intelligence history?")) {
                  setExchanges([]);
                  localStorage.removeItem("dead_star_history");
                }
              }}
              className="text-[11px] font-subheading font-bold uppercase tracking-widest text-muted hover:text-destructive transition-colors"
            >
              Clear History
            </button>
          </div>
        )}
      </div>

      <main className="flex-1 flex flex-col pt-32 pb-48 min-h-screen">
        <AnimatePresence mode="wait">
          {appState === "idle" ? (
            <motion.div
              key="idle"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="max-w-[1000px] mx-auto w-full px-6"
            >
              <div className="flex flex-col items-center gap-10 mb-20 mt-12">
                <GemmaLogo size={120} className="drop-shadow-2xl" priority />
                <div className="text-center relative">
                  <div className="hero-glow" />
                  <h1 className="halaska-display mb-6 tracking-tighter relative z-10">
                    DEAD STAR
                  </h1>
                  <p className="text-2xl md:text-3xl font-body font-medium text-muted leading-tight max-w-[700px] mx-auto relative z-10">
                    The first reasoning interface designed to <span className="text-foreground font-semibold">partner with your logic</span>. 
                    Optimized for <span className="text-primary font-bold">Gemma 4 Expert Intelligence</span>.
                  </p>
                </div>
              </div>

              {/* Intelligence Upload Hero Card */}
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                onClick={() => {
                  const fileInput = document.querySelector('input[type="file"]') as HTMLInputElement;
                  fileInput?.click();
                }}
                className="group relative cursor-pointer mb-20 p-[1px] rounded-[48px] bg-gradient-to-br from-primary/30 via-white/10 to-primary/30 hover:from-primary/50 transition-all duration-700 overflow-hidden shadow-2xl"
              >
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_120%,rgba(99,102,241,0.1),transparent)] pointer-events-none" />
                <div className="absolute inset-0 opacity-10 group-hover:opacity-20 transition-opacity duration-700 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:40px_40px]" />
                
                <div className="bg-background/40 backdrop-blur-3xl rounded-[47px] p-12 md:p-20 flex flex-col md:flex-row items-center gap-16 border border-white/5 relative z-10">
                  <div className="flex-1 text-left">
                    <div className="flex items-center gap-3 mb-8">
                      <div className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                      <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-[10px] font-bold uppercase tracking-[0.3em] border border-primary/20">Multimodal Core</span>
                    </div>
                    <h2 className="text-5xl md:text-6xl font-subheading font-bold tracking-tighter mb-8 leading-[0.85] italic">
                      START A <br/> <span className="text-primary not-italic">CONSULTATION</span>.
                    </h2>
                    <p className="text-xl md:text-2xl text-muted font-body leading-relaxed max-w-lg">
                      Share an architecture diagram, a complex flowchart, or a technical challenge. 
                      Gemma 4 will collaborate with you to map out every reasoning step.
                    </p>
                  </div>
                  
                  <div className="w-full md:w-auto">
                    <div className="w-72 h-72 rounded-[40px] border-2 border-dashed border-primary/20 flex flex-col items-center justify-center gap-6 group-hover:border-primary/50 transition-all duration-500 bg-primary/[0.02] shadow-inner">
                      <div className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center group-hover:scale-110 group-hover:bg-primary/20 transition-all duration-700 shadow-2xl">
                        <Camera className="w-12 h-12 text-primary" />
                      </div>
                      <div className="text-center">
                        <span className="block text-xs font-bold uppercase tracking-[0.3em] text-primary mb-1">Share Context</span>
                        <span className="block text-[10px] text-muted font-subheading uppercase tracking-widest opacity-50">Drag & Drop Supported</span>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>

              {/* Scenarios Library Section */}
              <div className="mb-24">
                <div className="flex items-center gap-3 mb-8">
                  <div className="w-1.5 h-6 bg-primary rounded-full shadow-[0_0_10px_rgba(var(--primary),0.5)]" />
                  <h2 className="text-xs font-subheading font-bold uppercase tracking-[0.3em] text-muted/60">Service Categories</h2>
                </div>
                
                <ScenarioHUD onSelect={(prompt) => {
                  setUserInput(prompt);
                }} />
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="chat"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.2 }}
              className="max-w-[760px] mx-auto w-full px-6 flex flex-col gap-8"
            >
              {/* Previous Exchanges */}
              {exchanges.map((ex) => (
                <div key={ex.id} className="flex flex-col gap-6">
                  <UserRow message={ex.userMessage} image={ex.image} />
                  <AIRow>
                    <AnswerPanel answer={ex.answer} isStreaming={false} />
                    <div className="flex flex-col gap-2">
                      <InfluenceScore
                        score={ex.influenceScore}
                        totalThoughts={ex.totalThoughts}
                        changedThoughts={ex.changedThoughts}
                      />
                      <button 
                        onClick={() => downloadDossier(ex)}
                        className="w-full py-2 rounded-xl border border-primary/20 bg-primary/5 text-[10px] font-bold uppercase tracking-[0.2em] text-primary hover:bg-primary/10 transition-all flex items-center justify-center gap-2"
                      >
                        <FileCode className="w-3 h-3" />
                        Export Insight Report
                      </button>
                    </div>
                  </AIRow>
                </div>
              ))}

              {/* Current Active Exchange */}
              <div className="flex flex-col gap-6">
                <UserRow message={currentMessage} image={currentImage} />
                
                <AnimatePresence>
                  {(appState === "streaming" || appState === "locked" || appState === "collapsed") && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      className="ml-14 relative"
                    >
                      {/* Logic Intervention Tutorial Tooltip */}
                      {appState === "locked" && (
                        <motion.div 
                          initial={{ opacity: 0, x: 20 }}
                          animate={{ opacity: 1, x: 0 }}
                          className="absolute -right-64 top-0 w-60 p-4 rounded-2xl bg-primary text-primary-foreground shadow-2xl z-[400] hidden lg:block"
                        >
                          <div className="flex flex-col gap-2">
                            <span className="text-[10px] font-bold uppercase tracking-widest opacity-70">Collaboration Guide</span>
                            <p className="text-xs font-bold leading-tight">INSIGHT AVAILABLE</p>
                            <p className="text-[11px] leading-snug opacity-90">Click any reasoning node to **refine the reasoning flow**. You can manually guide the steps before finalizing the results.</p>
                            <div className="mt-2 flex items-center gap-2">
                              <span className="w-4 h-4 rounded-full bg-white/20 flex items-center justify-center text-[8px] font-bold">1</span>
                              <div className="h-px flex-1 bg-white/20" />
                              <span className="text-[9px] font-bold uppercase">Guide Now</span>
                            </div>
                          </div>
                          {/* Triangle */}
                          <div className="absolute top-6 -left-2 w-4 h-4 bg-primary rotate-45" />
                        </motion.div>
                      )}

                      <ThoughtStream
                        thoughts={currentThoughts}
                        setThoughts={setCurrentThoughts}
                        isStreaming={appState === "streaming"}
                        onCollapse={handleAnswer}
                      />
                    </motion.div>
                  )}
                </AnimatePresence>

                {(appState === "collapsed" || appState === "answered") && currentAnswer && (
                  <AIRow>
                    <AnswerPanel answer={currentAnswer} isStreaming={appState === "collapsed"} />
                    {appState === "answered" && (
                      <InfluenceScore
                        score={calculateInfluence(
                          currentThoughts.map(t => t.originalContent ?? t.content),
                          currentThoughts.map(t => t.content)
                        )}
                        totalThoughts={currentThoughts.length}
                        changedThoughts={currentThoughts.filter(t => t.originalContent !== null && t.originalContent !== t.content).length}
                      />
                    )}
                  </AIRow>
                )}

                {appState === "error" && (
                  <AIRow>
                    <div className="p-6 rounded-2xl bg-destructive/5 border border-destructive/20 flex flex-col items-center gap-4 text-center">
                      <div className="w-12 h-12 rounded-full bg-destructive/10 flex items-center justify-center text-destructive">
                        <Sparkles className="w-6 h-6" />
                      </div>
                      <div>
                        <h3 className="font-subheading font-bold text-foreground">Intervention Failed</h3>
                        <p className="text-sm text-muted font-body mt-1">The machine resisted the collapse. This usually happens when the reasoning is too unstable.</p>
                      </div>
                      <button
                        onClick={(e) => {
                          e.currentTarget.disabled = true;
                          e.currentTarget.innerText = "Retrying...";
                          handleRetry();
                        }}
                        className="relative z-50 px-6 py-2 bg-foreground text-background rounded-full text-sm font-bold hover:scale-105 transition-all disabled:opacity-50"
                      >
                        Retry Intelligence
                      </button>
                    </div>
                  </AIRow>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
        <div ref={endRef} />
      </main>

      <ChatInput
        value={userInput}
        onChange={setUserInput}
        onSend={handleSend}
        disabled={appState === "streaming" || appState === "locked" || appState === "collapsed"}
        isVisible={!isFooterInView}
      />

      {/* Minimalist 2-Column Footer */}
      <footer ref={footerRef} className="w-full bg-[#E5E7EB] dark:bg-[#1A1A1A] border-t border-black/10 dark:border-white/10 text-black dark:text-white font-sans mt-auto">
        <div className="grid grid-cols-1 md:grid-cols-2">
          {/* Left Column */}
          <div className="p-8 md:p-16 border-b md:border-b-0 md:border-r border-black/10 dark:border-white/10 flex flex-col justify-between min-h-[300px]">
            <div className="flex items-center gap-4">
              <GemmaLogo size={48} className="invert dark:invert-0" />
              <span className="text-4xl font-subheading font-medium tracking-tighter uppercase">Dead Star</span>
            </div>
            <div className="flex flex-col gap-2 mt-8">
              <div className="text-xs text-muted font-body font-medium uppercase tracking-widest mb-4">
                ©2026 Dead Star, Inc. All Rights Reserved.
              </div>
              <a 
                href="https://calendly.com/ashandev/new-meeting" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center px-8 py-4 rounded-full bg-primary text-primary-foreground font-subheading font-bold text-lg hover:scale-105 active:scale-95 transition-all shadow-xl shadow-primary/20 w-fit"
              >
                Book a Call
              </a>
            </div>
          </div>

          {/* Right Column */}
          <div className="p-8 md:p-16 flex flex-col justify-between min-h-[300px]">
            <div className="flex flex-col gap-4">
              <a href="https://dev.to/itxashancode" target="_blank" rel="noopener noreferrer" className="text-2xl font-subheading font-medium hover:opacity-50 transition-opacity">Dev.to</a>
              <a href="https://github.com/itxashancode" target="_blank" rel="noopener noreferrer" className="text-2xl font-subheading font-medium hover:opacity-50 transition-opacity">GitHub</a>
              <a href="https://linktr.ee/itxashanvibes" target="_blank" rel="noopener noreferrer" className="text-2xl font-subheading font-medium hover:opacity-50 transition-opacity">Linktree</a>
              <a href="https://x.com/ASHAN868904" target="_blank" rel="noopener noreferrer" className="text-2xl font-subheading font-medium hover:opacity-50 transition-opacity">X</a>
            </div>
            <div className="flex justify-start md:justify-end">
              <a href="#" className="text-xs text-muted font-body font-medium uppercase tracking-widest hover:opacity-100 transition-opacity">
                Privacy Notice
              </a>
            </div>
          </div>
        </div>
      </footer>
      </ClickSpark>
    </div>
  );
}


const UserRow = memo(({ message, image }: { message?: string; image?: ImageAttachment }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex items-start gap-4"
    >
      <Avatar className="w-10 h-10 border border-border shadow-sm">
        <AvatarFallback className="bg-muted text-muted font-subheading text-xs font-bold">U</AvatarFallback>
      </Avatar>
      <div className="flex flex-col gap-3 flex-1 min-w-0">
        {image && (
          <div className="w-fit rounded-2xl overflow-hidden border border-border shadow-lg">
            <Image src={image.previewUrl} alt="User input" width={300} height={300} className="max-w-[300px] h-auto object-cover" unoptimized />
          </div>
        )}
        {message && (
          <div className="text-[17px] font-body font-medium text-foreground leading-relaxed break-words">
            {message}
          </div>
        )}
      </div>
    </motion.div>
  );
});

UserRow.displayName = "UserRow";

const AIRow = memo(({ children }: { children: React.ReactNode }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex items-start gap-4"
    >
      <div className="mt-1">
        <GemmaLogo size={32} />
      </div>
      <div className="flex flex-col gap-2 flex-1 min-w-0">
        {children}
      </div>
    </motion.div>
  );
});

AIRow.displayName = "AIRow";

const ScenarioHUD = memo(({ onSelect }: { onSelect: (prompt: string) => void }) => {
  const scenarios = [
    {
      title: "Analyze System Architecture",
      desc: "Deconstruct a complex system.",
      prompt: "Analyze a modern microservices architecture with an API gateway, Redis caching layer, and Postgres database. Map out the potential reasoning flaws in data consistency during a network partition.",
      icon: "Cpu"
    },
    {
      title: "Plan a Distributed Database",
      desc: "Design scalable data storage.",
      prompt: "Design a globally distributed database topology. Map the intelligence nodes for handling eventual consistency versus strong consistency trade-offs.",
      icon: "Network"
    },
    {
      title: "Debug a Memory Leak",
      desc: "Identify elusive code flaws.",
      prompt: "Trace the reasoning path for diagnosing a severe memory leak in a Node.js Edge runtime environment. What are the key diagnostic nodes?",
      icon: "Zap"
    }
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      {scenarios.map((s, i) => (
        <motion.div
          key={i}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 + i * 0.1 }}
          onClick={() => onSelect(s.prompt)}
          className="group relative cursor-pointer p-8 rounded-[32px] bg-muted/30 border border-white/5 hover:bg-muted/50 hover:border-primary/30 transition-all duration-500 overflow-hidden"
        >
          <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-100 transition-opacity">
            <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center">
              <ChevronRight className="w-4 h-4 text-primary" />
            </div>
          </div>
          <h3 className="text-lg font-subheading font-bold text-foreground mb-2 tracking-tight group-hover:text-primary transition-colors">{s.title}</h3>
          <p className="text-sm text-muted font-body leading-relaxed">{s.desc}</p>
        </motion.div>
      ))}
    </div>
  );
});

ScenarioHUD.displayName = "ScenarioHUD";
