"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, FileCode } from "lucide-react";
import dynamic from "next/dynamic";
import { UserRow, AIRow } from "@/components/chat/MessageRows";
import { useReasoningStore, Exchange } from "@/store/useReasoningStore";
import { Thought } from "@/components/ThoughtStream";
import { calculateInfluence } from "@/lib/diff";
import { ImageAttachment } from "@/components/ChatInput";
import { RefObject } from "react";
import EntropyGraph from "@/components/chat/EntropyGraph";

const ThoughtStream = dynamic(() => import("@/components/ThoughtStream"), { ssr: false });

const AnswerPanel = dynamic(() => import("@/components/AnswerPanel"), { ssr: false });
const InfluenceScore = dynamic(() => import("@/components/InfluenceScore"), { ssr: false });

interface ChatContainerProps {
  answerRef: RefObject<HTMLDivElement | null>;
  handleRetry: () => void;
}


export default function ChatContainer({
  answerRef,
  handleRetry
}: ChatContainerProps) {
  const {
    exchanges,
    currentMessage,
    currentImage,
    appState,
    currentThoughts,
    setCurrentThoughts,
    currentAnswer,
    handleAnswer,
    entropyData
  } = useReasoningStore();

  
  const downloadDossier = (ex: Exchange) => {
    const content = `
# MIDNIGHT-NEXUS: INTELLIGENCE DOSSIER
ID: ${ex.id}
Timestamp: ${new Date().toISOString()}

## USER INPUT
${ex.userMessage}
${ex.image ? `[Multimodal Attachment: ${ex.image.mimeType}]` : ""}

## INTERCEPTED REASONING NODES
${ex.thoughts.map((t: Thought, i: number) => `
### Node ${i + 1} ${t.originalContent && t.originalContent !== t.content ? "(INTERCEPTED)" : ""}
${t.content}
${t.originalContent && t.originalContent !== t.content ? `\n*Original Machine Intent:* ${t.originalContent}` : ""}
`).join("\n")}

## SYNTHESIZED INTELLIGENCE
${ex.answer}

## METRICS
- Influence Score: ${ex.influenceScore}%
- Nodes Processed: ${ex.totalThoughts}
- Human Interventions: ${ex.changedThoughts}

---
Generated by MIDNIGHT-NEXUS (Nexus Reasoning Protocol)
`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dead_star_dossier_${ex.id.slice(0, 8)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.2 }}
      className="max-w-[760px] mx-auto w-full px-4 md:px-6 flex flex-col gap-8"
    >
      {/* Previous Exchanges */}
      {exchanges.map((ex) => (
        <div key={ex.id} className="flex flex-col gap-6">
          <UserRow message={ex.userMessage} image={ex.image} />
          <AIRow>
            <AnswerPanel answer={ex.answer} isStreaming={false} />
            <div className="flex flex-col gap-2">
              <InfluenceScore
                score={ex.influenceScore}
                totalThoughts={ex.totalThoughts}
                changedThoughts={ex.changedThoughts}
              />
              <button
                onClick={() => downloadDossier(ex)}
                className="w-full py-2 rounded-xl border border-primary/20 bg-primary/5 text-[10px] font-bold uppercase tracking-[0.2em] text-primary hover:bg-primary/10 transition-all flex items-center justify-center gap-2"
              >
                <FileCode className="w-3 h-3" />
                Export Insight Report
              </button>
            </div>
          </AIRow>
        </div>
      ))}

      {/* Current Active Exchange */}
      <div className="flex flex-col gap-6">
        {currentMessage && <UserRow message={currentMessage} image={currentImage} />}

        <AnimatePresence>
          {(appState === "streaming" || appState === "locked" || appState === "collapsed") && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              className="ml-6 md:ml-14 relative flex flex-col gap-6"

            >
              {/* Intelligence Stream Metrics HUD */}
              {(appState === "streaming" || appState === "locked") && entropyData.length > 0 && (
                <div className="flex flex-col gap-4">
                  <EntropyGraph 
                    data={entropyData} 
                    labels={entropyData.map((_, i) => i.toString())} 
                  />
                  
                  
                </div>
              )}

              {/* Thought Stream */}

              <ThoughtStream
                thoughts={currentThoughts}
                setThoughts={setCurrentThoughts}
                isStreaming={appState === "streaming"}
                onCollapse={handleAnswer}
              />
            </motion.div>
          )}
        </AnimatePresence>

        {(appState === "collapsed" || appState === "answered") && currentAnswer && (
          <AIRow>
            <div ref={answerRef}>
              <AnswerPanel answer={currentAnswer} isStreaming={appState === "collapsed"} />
              {appState === "answered" && (
                <InfluenceScore
                  score={calculateInfluence(
                    currentThoughts.map(t => t.originalContent ?? t.content),
                    currentThoughts.map(t => t.content)
                  )}
                  totalThoughts={currentThoughts.length}
                  changedThoughts={currentThoughts.filter(t => t.originalContent !== null && t.originalContent !== t.content).length}
                />
              )}
            </div>
          </AIRow>
        )}

        {appState === "error" && (
          <AIRow>
            <div className="p-6 rounded-2xl bg-destructive/5 border border-destructive/20 flex flex-col items-center gap-4 text-center">
              <div className="w-12 h-12 rounded-full bg-destructive/10 flex items-center justify-center text-destructive">
                <Sparkles className="w-6 h-6" />
              </div>
              <div>
                <h3 className="font-subheading font-bold text-foreground">Intervention Failed</h3>
                <p className="text-sm text-muted font-body mt-1">The machine resisted the collapse. This usually happens when the reasoning is too unstable.</p>
              </div>
              <button
                onClick={(e) => {
                  e.currentTarget.disabled = true;
                  e.currentTarget.innerText = "Retrying...";
                  handleRetry();
                }}
                className="relative z-50 px-6 py-2 bg-foreground text-background rounded-full text-sm font-bold hover:scale-105 transition-all disabled:opacity-50"
                aria-label="Retry reasoning process"
              >
                Retry Intelligence
              </button>
            </div>
          </AIRow>
        )}
      </div>
    </motion.div>
  );
}
